services:
  nginx:
    image: nginx:1.27-alpine
    container_name: findash-nginx
    restart: unless-stopped
    volumes:
      - ./infra/nginx/findash.seudominio.com.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    network_mode: host
